### ISSUE TITLE
Can't cabal build with lens-4.4.0.1, HROOT-0.8  on the Mac OS Mavericks with ghc-7.8.3, cabal-1.20.0.2

### ISSUE THREAD

**Issue by enoshima** [wavewave/HROOT#3]
Hello,

I tried to use HROOT with Control.Lens in my code, but failed at cabal build due to linking shared libraries.
Here is my code

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
$ cat TestLens.hs
{-# LANGUAGE TemplateHaskell #-}

module TestLens
where

import Control.Lens
import HROOT

data AAA = AAA
  { _data :: Double
  } deriving (Show,Eq,Read)
$(makeLenses ''AAA)
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

I tried building cabal package
cabal init
cabal configure
Then, after cabal build,
I got following linking error.

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
.....
Loading package zlib-0.5.4.1 ... linking ... done.
Loading package lens-4.4.0.1 ... linking ... done.
Loading package fficxx-runtime-0.2 ... linking ... done.
Loading package HROOT-core-0.8 ...
<no location info>:
    <command line>: can't load .so/.DLL for: libGui.dylib (dlopen(libGui.dylib, 9): image not found)
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

If I remove the line
$(makeLenses ''AAA)
then it worked. This means Template Haskell is not suitable ROOT or so, I imagine.
Do you have any idea to solve this issue?

my environment is
Mac OS Mavericks with ghc-7.8.3, cabal-1.20.0.2

Thank you in advance
enoshima

**Comment by wavewave** [comment]
no more problematic
