### ISSUE TITLE
Linking problem on MacOS

### ISSUE THREAD

**Issue by drever** [wavewave/HROOT#4]
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TypeSynonymInstances #-}
{-# LANGUAGE FlexibleInstances #-}
module Main where

import Control.Monad

import Data.Random 
import Data.Random.Distribution.Normal
import Data.String

import Foreign.C.Types

import System.IO.Unsafe
import Foreign.C.String

import HROOT
instance IsString CString where
    fromString str = unsafePerformIO $ newCString str

main :: IO () 
main = do 
    tcanvas <- newTCanvas "Test" "Test" 640 480
    h1 <- newTH1F "test" "test" 100 (-5.0) 5.0 

```
let dist = (Normal (0 :: Double) (2 :: Double)) 

let go n | n < 0 = return () 
         | otherwise = do 
               histfill dist h1
               go (n-1) 

go 1000000
draw h1 ""
saveAs tcanvas "random1d.pdf" ""
saveAs tcanvas "random1d.jpg" "" 
```

histfill :: Normal Double -> TH1F ->  IO () 
histfill dist hist = do 
   x <- sample dist 
   fill1 hist $ realToFrac x
   return ()

**Comment by wavewave** [comment]
no more problematic
